import {it,expect,afterEach} from 'vitest';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {Workspaces} from '../src/host/workspaces.js';import {HostServer} from '../src/host/server.js';import {NativeAgentFactory} from '../src/host/native/factory.js';import {CodexSessionFactory} from '../src/host/codex-adapter.js';
const cleanup:Array<()=>Promise<unknown>>=[];afterEach(async()=>{for(const f of cleanup.reverse())await f();cleanup.length=0;});
it.each(['native','handoff'] as const)('runs %s Fork through HTTP into a durable independent Codex session',async mode=>{
 const root=await mkdtemp(join(tmpdir(),'coffee-fork-native-'));cleanup.push(()=>rm(root,{recursive:true,force:true}));const source=join(root,'source');await mkdir(source);const exec=promisify(execFile);
 const git=(args:string[])=>exec('git',['-c','user.name=Test','-c','user.email=test@example.invalid',...args],{cwd:source});await git(['init','-b','main']);await writeFile(join(source,'code.txt'),'base');await git(['add','.']);await git(['commit','-m','base']);await git(['clone','--bare',source,join(root,'remote.git')]);
 const ws=new Workspaces(join(root,'projects'),{taskRoot:join(root,'tasks')});const project=await ws.registerProject('p',join(root,'remote.git'));const task=await ws.createConversation(project.id,'main',randomUUID(),'codex');
 const factory=new NativeAgentFactory({workspaces:ws,pi:{list:async()=>[],delete:async()=>false,create:async()=>{throw Error('Pi unused');}},codex:{command:process.execPath,args:[resolve('test/fixtures/fake-codex.mjs')]},codexSessionFactory:(id,cwd,onBound,environment)=>new CodexSessionFactory({cwd,cliPath:process.execPath,commandArgs:[resolve('test/fixtures/fake-codex-app-server.mjs')],codexHome:join(root,'codex'),mappingFile:join(root,'maps',id+'.json'),envForSession:environment,onBound:async(_host,native)=>onBound(native)})});cleanup.push(()=>factory.close());
 const original=await factory.create({sessionId:task.id});await original.setModel('codex','gpt-fake');await original.setThinkingLevel('high');await original.prompt('Original requirement with pending user choice');await expect.poll(async()=>(await original.getHistory()).entries.some(e=>e.kind==='assistant')).toBe(true);
 await original.setContextPreset?.('maximum');const before=await original.getHistory();await original.stop();const host=new HostServer({port:0,token:'fixture',factory,workspaces:ws});await host.start();cleanup.push(()=>host.close());
 const target=randomUUID();const response=await fetch(`http://127.0.0.1:${host.address().port}/api/workspace`,{method:'POST',headers:{authorization:'Bearer fixture','content-type':'application/json'},body:JSON.stringify({action:'fork',id:task.id,targetId:target,mode,acceptDrift:true})});expect(response.status,await response.clone().text()).toBe(202);
 await expect.poll(async()=>(await ws.lookup(target))?.fork?.status,{timeout:10000}).toBe('completed');
 const child=await factory.create({sessionId:target});cleanup.push(()=>child.stop());const history=await child.getHistory();
 if(mode==='native')expect(history.entries).toEqual(before.entries);else{expect(history.entries.some(e=>e.kind==='user'&&e.text==='Original requirement with pending user choice')).toBe(false);expect(await readFile(join(await ws.dataRoot(target),'fork','handoff.md'),'utf8')).toContain('Pending: run tests');}
 expect(await child.getModels()).toMatchObject({current:{provider:'codex',id:'gpt-fake'},thinkingLevel:'high',context:{preset:'maximum'}});
 const reopened=await factory.create({sessionId:task.id});cleanup.push(()=>reopened.stop());expect(await reopened.getHistory()).toEqual(before);expect((await ws.lookup(task.id))?.nativeBinding?.id).not.toBe((await ws.lookup(target))?.nativeBinding?.id);
});
