import {it,expect,afterEach} from 'vitest';import {mkdtemp,mkdir,readFile,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {SessionManager} from '@earendil-works/pi-coding-agent';import {RpcPiSessionFactory} from '../src/host/pi-adapter.js';import {NativeAgentFactory} from '../src/host/native/factory.js';import {Workspaces} from '../src/host/workspaces.js';import {HostServer} from '../src/host/server.js';
let host:HostServer,root='';afterEach(async()=>{await host?.close();if(root)await rm(root,{recursive:true,force:true});});
it('invokes the pinned Handoff RPC only on a native Pi copy, preserving Chat and source transcript',async()=>{
 root=await mkdtemp(join(tmpdir(),'coffee-pi-handoff-fork-'));const ws=new Workspaces(join(root,'projects'),{taskRoot:join(root,'tasks')});const source=await ws.createChatConversation();const store=join(root,'sessions');await mkdir(store);
 const original=SessionManager.create(source.cwd,store,{id:source.id});original.appendMessage({role:'user',content:'Original question',timestamp:Date.now()});original.appendMessage({role:'assistant',content:[{type:'text',text:'Original reply'}],api:'openai-completions',provider:'fake',model:'fake-mini',usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:'stop',timestamp:Date.now()});
 const before=await readFile(original.getSessionFile()!,'utf8'),log=join(root,'rpc.jsonl');
 const pi=new RpcPiSessionFactory({cwd:source.cwd,sessionDir:store,cliPath:resolve('test/fixtures/fake-pi-rpc.mjs'),env:{FAKE_HANDOFF:'success',FIXTURE_FORK_RPC_LOG:log},envForSession:id=>ws.runtimeEnvironment(id),cwdForSession:id=>ws.file(id,'')});
 const factory=new NativeAgentFactory({pi,workspaces:ws});host=new HostServer({port:0,token:'fixture',factory,workspaces:ws});await host.start();const target=randomUUID();
 const response=await fetch(`http://127.0.0.1:${host.address().port}/api/workspace`,{method:'POST',headers:{authorization:'Bearer fixture','content-type':'application/json'},body:JSON.stringify({action:'fork',id:source.id,targetId:target,mode:'handoff',acceptDrift:true})});expect(response.status,await response.clone().text()).toBe(202);
 await expect.poll(async()=>(await ws.lookup(target))?.fork?.status).toBe('completed');expect((await ws.lookup(target))?.workspaceKind).toBe('chat');expect((await ws.lookup(target))?.engine).toBe('pi');
 const calls=(await readFile(log,'utf8')).trim().split('\n').map(line=>JSON.parse(line));expect(calls).toHaveLength(1);expect(calls[0]).toMatchObject({command:'compact',marker:'context-handoff:manual:v1'});expect(calls[0].path).toContain(target);expect(calls[0].path).not.toBe(original.getSessionFile());expect(await readFile(original.getSessionFile()!,'utf8')).toBe(before);
});
